---
abstract: 'Mojolicious + http://jquery.com/'
author:
  - 'Francesco Ferro <dgikiller@users.noreply.github.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mojolicious-Plugin-JQuery
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: '2'
  File::Find: '3'
  Mojolicious: '0'
  Mojolicious::Plugin::AssetPack: '0'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/dgikiller/mojolicious-plugin-jquery/issues
  homepage: https://github.com/dgikiller/mojolicious-plugin-jquery
  repository: https://github.com/dgikiller/mojolicious-plugin-jquery.git
version: '2.11002'
