---
abstract: 'Mojolicious + http://jquery.com/'
author:
  - 'skullbocks <dgikille@gmail.com>'
build_requires:
  Test::More: 0.96
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.94, CPAN::Meta::Converter version 2.133380'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-JQuery
no_index:
  directory:
    - t
    - inc
requires:
  File::Basename: 0.96
  File::Find: 0.96
  Mojolicious: 5.00
  Mojolicious::Plugin::AssetPack: 0.21
  perl: 5.008005
resources:
  bugtracker: https://github.com/dgikiller/mojolicious-plugin-jquery/issues
  homepage: https://github.com/dgikiller/mojolicious-plugin-jquery
  repository: https://github.com/dgikiller/mojolicious-plugin-jquery.git
version: 2.11001
